### ISSUE TITLE
ncm whitelist --add doesn't work

### ISSUE THREAD

**Issue by mnedelko** [nodesource/ncm-cli#161] opened 2019-06-13 22:46 UTC
'ncm whitelist --add' throws the following error:

![image](https://user-images.githubusercontent.com/6106392/59472163-6e154300-8df2-11e9-9b1d-48a2b452fabd.png)

I am:
- logged into NodeSource account
- upgraded to latest ncm

**Comment by Fishrock123** [comment] 2019-06-15 01:03
Yeah this is technically just a duplicate of https://github.com/nodesource/ncm-cli/issues/160

**Closed by Fishrock123** 2019-06-15 01:03 UTC
Labels: Sev2, Type: Bug, Type: Duplicate
