### ISSUE TITLE
display dependency chains in --long

### ISSUE THREAD

**Issue by pmuellr** [nodesource/ncm-cli#120] opened 2019-03-13 17:49 UTC
The report commands lists packages without indicating the chain of packages that led to this package being included.  That should really be part of the `ncm-cli report --long` output.

**Comment by Fishrock123** [comment] 2019-03-13 18:06
This is... sort of a duplicate of https://github.com/nodesource/ncm-cli/issues/74

We had the idea to do this, but in the `details` command.

Note that on large repos, long reports can already exceed terminal default scrollback lengths...

**Comment by Fishrock123** [comment] 2019-03-22 23:59
There's a lot of other information you're going to have to run `details` for anyways, so I think for now we're just going to stick with doing this in there. Pr for that is at https://github.com/nodesource/ncm-cli/pull/128

**Closed** 2019-03-25 23:41 UTC
Labels: Type: Feature
